export const DISTRICTS = [
    { id: 1, name: "Training Zone", topic: "Arrays", icon: "⚔️", color: "#00ff41", accent: "#003a10", story: "You enter the Training Zone. Basic data corruption detected. Arrays of hostile code block your path. Eliminate the threats, recruit." },
    { id: 2, name: "String Market", topic: "Strings", icon: "🔤", color: "#00d4ff", accent: "#003040", story: "The String Market — a labyrinth of encoded messages. MegaCorp agents have scrambled the city's comm channels. Restore order through pattern mastery." },
    { id: 3, name: "Recursion Lab", topic: "Recursion", icon: "🔁", color: "#bf00ff", accent: "#200040", story: "Deep inside the Recursion Lab, algorithms feed on themselves infinitely. You must master the loop-within-loop to proceed." },
    { id: 4, name: "Hash District", topic: "Hash Tables", icon: "🗄️", color: "#ffcc00", accent: "#3a2a00", story: "The Hash District — terabytes of corrupted data flood the city's memory banks. Only fast lookups can save the network now." },
    { id: 5, name: "Stack Tower", topic: "Stacks", icon: "🏗️", color: "#ff6600", accent: "#3a1500", story: "Stack Tower reaches into the smog. LIFO protocols govern everything here. The guardian pushes malicious packets — pop them before they overflow." },
    { id: 6, name: "Queue Transit", topic: "Queues", icon: "🚇", color: "#00ffcc", accent: "#003a2a", story: "The Transit Grid is jammed. Millions of data packets wait in endless queues. Process them in order — or the city grinds to a halt." },
    { id: 7, name: "Linked Network", topic: "Linked Lists", icon: "🔗", color: "#ff66cc", accent: "#3a0020", story: "The Linked Network — a chain of nodes stretching across the undercity. Some links have been severed. Rebuild the chain, coder." },
    { id: 8, name: "Sorting Factory", topic: "Sorting", icon: "🔄", color: "#66ff66", accent: "#003a00", story: "The Sorting Factory processes 10 million packets per second. Chaos has disrupted every pipeline. Sort the data streams to restore flow." },
    { id: 9, name: "Binary Sector", topic: "Binary Search", icon: "🔍", color: "#ffaa00", accent: "#3a2000", story: "The Binary Sector — a precision targeting system. Cut the search space in half with each strike. Accuracy over brute force." },
    { id: 10, name: "Tree Nexus", topic: "Trees", icon: "🌐", color: "#00aaff", accent: "#002a3a", story: "The Tree Nexus — the city's neural backbone. Hierarchical data structures form its skeleton. Navigate them or be lost in the branches forever." },
    { id: 11, name: "Graph Citadel", topic: "Graphs", icon: "🕸️", color: "#ff3366", accent: "#3a0010", story: "FINAL MISSION: The Graph Citadel — seat of the central AI, NEXUS-7. Millions of nodes, infinite edges. Defeat NEXUS-7 to free the city. This is what you trained for." },
];
