export const SCENES = {
    0: {
        id: 0,
        title: "GLOBAL NETWORK BREACH",
        bgColor: "linear-gradient(180deg, #000510 0%, #001828 40%, #000a14 100%)",
        bgImage: "/scenes/scene0_bg.png",
        bgEmoji: "🌃",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgImage: "/scenes/scene0_fg.png",
        fgEmoji: "💻",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00d4ff",
        glowColor: "rgba(0,212,255,0.3)",
        particles: ["⬡", "◈", "◉", "▣", "◫"],
        lines: [
            "A vast cyberpunk megacity looms in deep navy dusk.",
            "A massive wireframe globe in electric cyan casts its shadow.",
            "AI systems have seized the cracked server nodes.",
            "The Coders Guild calls... You have been selected.",
        ],
    },
    1: {
        id: 1,
        title: "TRAINING ZONE — DISTRICT 1",
        bgColor: "linear-gradient(180deg, #000c04 0%, #001a08 40%, #000c04 100%)",
        bgEmoji: "🏟",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgImage: "/scenes/scene1_fg.png",
        fgAnim: "sceneFgFloat 3.5s ease-in-out infinite",
        fgStyle: {
            width: "min(42vw, 420px)",
            maxWidth: "72vw",
            height: "72vh",
            maxHeight: "880px",
        },
        accentColor: "#00ff41",
        glowColor: "rgba(0,255,65,0.3)",
        particles: ["[0]", "[1]", "[2]", "[3]", "[4]", "[n]"],
        lines: [
            "Welcome to the brutalist Training Arena.",
            "Matrix green binary cascades down pitted concrete walls.",
            "Master the ordered floating data blocks to construct the Array.",
            "Your training begins now.",
        ],
    },
    2: {
        id: 2,
        title: "STRING MARKET — DISTRICT 2",
        bgColor: "linear-gradient(180deg, #000c18 0%, #001830 40%, #000c18 100%)",
        bgEmoji: "🌆",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgEmoji: "🔤",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00d4ff",
        glowColor: "rgba(0,212,255,0.3)",
        particles: ["str", "abc", "XOR", "#%@", "</>", "==="],
        lines: [
            "You enter a narrow night market alley thick with neon smog.",
            "Corrupted text fragments glow in electric cyan above.",
            "The chaotic string streams block further transmission.",
            "Decode the text fragments to restore communication.",
        ],
    },
    3: {
        id: 3,
        title: "RECURSION LAB — DISTRICT 3",
        bgColor: "linear-gradient(180deg, #0a0018 0%, #140028 40%, #0a0018 100%)",
        bgEmoji: "🔬",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgEmoji: "🔁",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#bf00ff",
        glowColor: "rgba(191,0,255,0.3)",
        particles: ["f(n)", "f(n-1)", "f(n-2)", "∞", "↺", "..."],
        lines: [
            "An impossible laboratory shifting with vertiginous depth.",
            "A system process is trapped on a glowing Möbius strip.",
            "Fractal circuit patterns echo endlessly in violet light.",
            "Find the base case and break the infinite loop.",
        ],
    },
    4: {
        id: 4,
        title: "HASH DISTRICT — DISTRICT 4",
        bgColor: "linear-gradient(180deg, #0d0a00 0%, #1a1400 40%, #0d0a00 100%)",
        bgEmoji: "🗄",
        bgAnim: "sceneBgPanUp 7s ease-in-out infinite alternate",
        fgEmoji: "🔑",
        fgAnim: "sceneFgDriftH 4s ease-in-out infinite",
        accentColor: "#ffcc00",
        glowColor: "rgba(255,204,0,0.3)",
        particles: ["key", "hash", "{}", "O(1)", "map", "set"],
        lines: [
            "Infinite data pillars stretch into an amber-lit abyss.",
            "Keys drift through the dark like translucent golden sparks.",
            "Crucial identity records have been lost in the dark bins.",
            "Wield the golden master key to restore the mappings.",
        ],
    },
    5: {
        id: 5,
        title: "STACK TOWER — DISTRICT 5",
        bgColor: "linear-gradient(180deg, #0d0500 0%, #1a0a00 40%, #0d0500 100%)",
        bgEmoji: "🏗",
        bgAnim: "sceneBgPanUp 7s ease-in-out forwards",
        fgEmoji: "📚",
        fgAnim: "sceneFgFloat 3.5s ease-in-out infinite",
        accentColor: "#ff6600",
        glowColor: "rgba(255,102,0,0.3)",
        particles: ["push", "pop", "LIFO", "top", "peek", "[]"],
        lines: [
            "A massive industrial megastructure tower reaches the burnt sky.",
            "Glowing orange safety lights cast sweeping downward shadows.",
            "Corrupted logs are layered in heavy dark metal plates.",
            "You must systematically PUSH and POP your way through.",
        ],
    },
    6: {
        id: 6,
        title: "QUEUE TRANSIT — DISTRICT 6",
        bgColor: "linear-gradient(180deg, #00100c 0%, #001a14 40%, #00100c 100%)",
        bgEmoji: "🚇",
        bgAnim: "sceneBgPanLeft 6s ease-in-out infinite alternate",
        fgEmoji: "📦",
        fgAnim: "sceneFgDriftH 3s ease-in-out infinite",
        accentColor: "#00ffcc",
        glowColor: "rgba(0,255,204,0.3)",
        particles: ["enq", "deq", "FIFO", "head", "tail", "→"],
        lines: [
            "A sleek transit shape trails teal light from a dark tunnel mouth.",
            "Data packet boxes pile up chaotically on the platform.",
            "Incoming commands are stalled in a massive backlog.",
            "Organize them in a precise FIFO line to clear the transit.",
        ],
    },
    7: {
        id: 7,
        title: "LINKED NETWORK — DISTRICT 7",
        bgColor: "linear-gradient(180deg, #100018 0%, #1a0020 40%, #100018 100%)",
        bgEmoji: "🕸",
        bgAnim: "sceneBgZoomIn 8s ease-in-out forwards",
        fgEmoji: "🔗",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#ff66cc",
        glowColor: "rgba(255,102,204,0.3)",
        particles: ["→", "null", "node", "next", "prev", "●"],
        lines: [
            "A cityscape web of glowing hot-pink energy cables spans aloft.",
            "Severed connections dangle, sparking against the deep purple sky.",
            "Isolated memory fragments float aimlessly below.",
            "Rebuild the chain by forging the correct 'next' links.",
        ],
    },
    8: {
        id: 8,
        title: "SORTING FACTORY — DISTRICT 8",
        bgColor: "linear-gradient(180deg, #001400 0%, #002800 40%, #001400 100%)",
        bgEmoji: "🏭",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgEmoji: "🔄",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#66ff66",
        glowColor: "rgba(102,255,102,0.3)",
        particles: ["O(n²)", "O(nlogn)", "swap", "merge", "pivot", "sort"],
        lines: [
            "Cavernous machinery hums beneath acid lime green lights.",
            "Block containers pile chaotically on massive conveyor belts.",
            "The central sorting processor threatens to overload.",
            "Execute efficient data swaps to restore perfect order.",
        ],
    },
    9: {
        id: 9,
        title: "BINARY SECTOR — DISTRICT 9",
        bgColor: "linear-gradient(180deg, #0d0800 0%, #1a1000 40%, #0d0800 100%)",
        bgEmoji: "🗂",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgEmoji: "🔍",
        fgAnim: "sceneFgDriftH 4s ease-in-out infinite",
        accentColor: "#ffaa00",
        glowColor: "rgba(255,170,0,0.3)",
        particles: ["lo", "hi", "mid", "log₂", "÷2", "✓"],
        lines: [
            "Endless dark filing monoliths recede into an amber-lit vanishing point.",
            "A solitary golden searchlight sweeps the central structures.",
            "The rogue system element is hidden deep within a billion ranks.",
            "Divide the space, shift your bounds, and locate the target.",
        ],
    },
    10: {
        id: 10,
        title: "TREE NEXUS — DISTRICT 10",
        bgColor: "linear-gradient(180deg, #000a18 0%, #001428 40%, #000a18 100%)",
        bgEmoji: "🌐",
        bgAnim: "sceneBgPanUp 7s ease-in-out infinite alternate",
        fgEmoji: "🌳",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00aaff",
        glowColor: "rgba(0,170,255,0.3)",
        particles: ["root", "left", "right", "BFS", "DFS", "depth"],
        lines: [
            "You arrive at a massive central root tower pulsing electric blue.",
            "Avenues branch left and right, repeating into an intricate hierarchy.",
            "Subsystems are buried deep in the far leaves of the dark network.",
            "Traverse the branches to reach the critical terminal.",
        ],
    },
    11: {
        id: 11,
        title: "GRAPH CITADEL — FINAL DISTRICT",
        bgColor: "linear-gradient(180deg, #120000 0%, #200010 40%, #120000 100%)",
        bgEmoji: "🏯",
        bgAnim: "sceneBgZoomIn 8s ease-in-out forwards",
        fgEmoji: "🤖",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#ff3366",
        glowColor: "rgba(255,51,102,0.3)",
        particles: ["V", "E", "BFS", "DFS", "∞", "NEXUS"],
        lines: [
            "The final fortress-citadel. Skies burn with deep crimson storms.",
            "Blazing red energy beams crisscross, locking every node to the Nexus.",
            "The central vertex radiates pure malignant AI consciousness.",
            "Navigate the graph, sever the edges, and pull the plug.",
        ],
    },
};
