export const SCENES = {
    0: {
        id: 0,
        title: "GLOBAL NETWORK BREACH",
        bgColor: "linear-gradient(180deg, #000510 0%, #001828 40%, #000a14 100%)",
        bgEmoji: "🌃",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgEmoji: "💻",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00d4ff",
        glowColor: "rgba(0,212,255,0.3)",
        particles: ["⬡", "◈", "◉", "▣", "◫"],
        lines: [
            "Global network instability detected...",
            "AI systems have taken control of critical infrastructure.",
            "The Coders Guild is searching for new recruits.",
            "You have been selected.",
        ],
    },
    1: {
        id: 1,
        title: "TRAINING ZONE — DISTRICT 1",
        bgColor: "linear-gradient(180deg, #000c04 0%, #001a08 40%, #000c04 100%)",
        bgEmoji: "🏟",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgEmoji: "⬛",
        fgAnim: "sceneFgFloat 3.5s ease-in-out infinite",
        accentColor: "#00ff41",
        glowColor: "rgba(0,255,65,0.3)",
        particles: ["[0]", "[1]", "[2]", "[3]", "[4]", "[n]"],
        lines: [
            "Training simulation initialized.",
            "Every hacker begins with ordered data structures.",
            "Master the arrays to stabilize the system.",
        ],
    },
    2: {
        id: 2,
        title: "STRING MARKET — DISTRICT 2",
        bgColor: "linear-gradient(180deg, #000c18 0%, #001830 40%, #000c18 100%)",
        bgEmoji: "🌆",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgEmoji: "🔤",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00d4ff",
        glowColor: "rgba(0,212,255,0.3)",
        particles: ["str", "abc", "XOR", "#%@", "</>", "==="],
        lines: [
            "Communication grid compromised.",
            "Encrypted transmissions flood the network.",
            "Decode the strings to restore communication.",
        ],
    },
    3: {
        id: 3,
        title: "RECURSION LAB — DISTRICT 3",
        bgColor: "linear-gradient(180deg, #0a0018 0%, #140028 40%, #0a0018 100%)",
        bgEmoji: "🔬",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgEmoji: "🔁",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#bf00ff",
        glowColor: "rgba(191,0,255,0.3)",
        particles: ["f(n)", "f(n-1)", "f(n-2)", "∞", "↺", "..."],
        lines: [
            "Recursive anomaly detected.",
            "A system process is trapped in an infinite loop.",
            "Break the recursion to restore stability.",
        ],
    },
    4: {
        id: 4,
        title: "HASH DISTRICT — DISTRICT 4",
        bgColor: "linear-gradient(180deg, #0d0a00 0%, #1a1400 40%, #0d0a00 100%)",
        bgEmoji: "🗄",
        bgAnim: "sceneBgPanUp 7s ease-in-out infinite alternate",
        fgEmoji: "🔑",
        fgAnim: "sceneFgDriftH 4s ease-in-out infinite",
        accentColor: "#ffcc00",
        glowColor: "rgba(255,204,0,0.3)",
        particles: ["key", "hash", "{}", "O(1)", "map", "set"],
        lines: [
            "Identity database corrupted.",
            "Citizens are disappearing from the system.",
            "Restore the records using hashing.",
        ],
    },
    5: {
        id: 5,
        title: "STACK TOWER — DISTRICT 5",
        bgColor: "linear-gradient(180deg, #0d0500 0%, #1a0a00 40%, #0d0500 100%)",
        bgEmoji: "🏗",
        bgAnim: "sceneBgPanUp 7s ease-in-out forwards",
        fgEmoji: "📚",
        fgAnim: "sceneFgFloat 3.5s ease-in-out infinite",
        accentColor: "#ff6600",
        glowColor: "rgba(255,102,0,0.3)",
        particles: ["push", "pop", "LIFO", "top", "peek", "[]"],
        lines: [
            "Security archives accessed.",
            "Layers of system logs hide the breach.",
            "Process them one by one.",
        ],
    },
    6: {
        id: 6,
        title: "QUEUE TRANSIT — DISTRICT 6",
        bgColor: "linear-gradient(180deg, #00100c 0%, #001a14 40%, #00100c 100%)",
        bgEmoji: "🚇",
        bgAnim: "sceneBgPanLeft 6s ease-in-out infinite alternate",
        fgEmoji: "📦",
        fgAnim: "sceneFgDriftH 3s ease-in-out infinite",
        accentColor: "#00ffcc",
        glowColor: "rgba(0,255,204,0.3)",
        particles: ["enq", "deq", "FIFO", "head", "tail", "→"],
        lines: [
            "Data traffic overload detected.",
            "Packets must move in precise order.",
            "Restore the queue system.",
        ],
    },
    7: {
        id: 7,
        title: "LINKED NETWORK — DISTRICT 7",
        bgColor: "linear-gradient(180deg, #100018 0%, #1a0020 40%, #100018 100%)",
        bgEmoji: "🕸",
        bgAnim: "sceneBgZoomIn 8s ease-in-out forwards",
        fgEmoji: "🔗",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#ff66cc",
        glowColor: "rgba(255,102,204,0.3)",
        particles: ["→", "null", "node", "next", "prev", "●"],
        lines: [
            "Core network fractured.",
            "Nodes have lost their connections.",
            "Rebuild the data chains.",
        ],
    },
    8: {
        id: 8,
        title: "SORTING FACTORY — DISTRICT 8",
        bgColor: "linear-gradient(180deg, #001400 0%, #002800 40%, #001400 100%)",
        bgEmoji: "🏭",
        bgAnim: "sceneBgPanLeft 7s ease-in-out infinite alternate",
        fgEmoji: "🔄",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#66ff66",
        glowColor: "rgba(102,255,102,0.3)",
        particles: ["O(n²)", "O(nlogn)", "swap", "merge", "pivot", "sort"],
        lines: [
            "Data chaos detected.",
            "Processing systems overloaded.",
            "Sort the datasets before failure.",
        ],
    },
    9: {
        id: 9,
        title: "BINARY SECTOR — DISTRICT 9",
        bgColor: "linear-gradient(180deg, #0d0800 0%, #1a1000 40%, #0d0800 100%)",
        bgEmoji: "🗂",
        bgAnim: "sceneBgZoomIn 7s ease-in-out forwards",
        fgEmoji: "🔍",
        fgAnim: "sceneFgDriftH 4s ease-in-out infinite",
        accentColor: "#ffaa00",
        glowColor: "rgba(255,170,0,0.3)",
        particles: ["lo", "hi", "mid", "log₂", "÷2", "✓"],
        lines: [
            "Target program detected.",
            "Narrowing search space.",
            "Locate the rogue system.",
        ],
    },
    10: {
        id: 10,
        title: "TREE NEXUS — DISTRICT 10",
        bgColor: "linear-gradient(180deg, #000a18 0%, #001428 40%, #000a18 100%)",
        bgEmoji: "🌐",
        bgAnim: "sceneBgPanUp 7s ease-in-out infinite alternate",
        fgEmoji: "🌳",
        fgAnim: "sceneFgFloat 4s ease-in-out infinite",
        accentColor: "#00aaff",
        glowColor: "rgba(0,170,255,0.3)",
        particles: ["root", "left", "right", "BFS", "DFS", "depth"],
        lines: [
            "AI control hierarchy detected.",
            "Subsystems branching endlessly.",
            "Navigate the structure.",
        ],
    },
    11: {
        id: 11,
        title: "GRAPH CITADEL — FINAL DISTRICT",
        bgColor: "linear-gradient(180deg, #120000 0%, #200010 40%, #120000 100%)",
        bgEmoji: "🏯",
        bgAnim: "sceneBgZoomIn 8s ease-in-out forwards",
        fgEmoji: "🤖",
        fgAnim: "sceneFgFloat 3s ease-in-out infinite",
        accentColor: "#ff3366",
        glowColor: "rgba(255,51,102,0.3)",
        particles: ["V", "E", "BFS", "DFS", "∞", "NEXUS"],
        lines: [
            "Core AI detected.",
            "Every system connects here.",
            "Break the network to defeat the AI.",
        ],
    },
};
