export const QUESTIONS = {
    1: [
        {
            id: "1a", title: "Two Sum", diff: "Easy", xp: 100,
            desc: "Given an array of integers `nums` and an integer `target`, return **indices** of two numbers that add up to target.\n\nAssume exactly one solution exists. Do not use the same element twice.",
            examples: [{ i: "nums=[2,7,11,15], target=9", o: "[0,1]", e: "nums[0]+nums[1]=2+7=9" }, { i: "nums=[3,2,4], target=6", o: "[1,2]" }],
            hints: ["Try using an object to store values you've seen", "For each num, check if (target-num) exists in your map", "Store {value: index} pairs as you iterate"],
            start: "function solve(nums, target) {\n  // Return array of two indices\n  \n}",
            tests: [{ l: "Basic case", r: (f) => f([2, 7, 11, 15], 9), e: [0, 1] }, { l: "Middle elements", r: (f) => f([3, 2, 4], 6), e: [1, 2] }, { l: "Duplicates", r: (f) => f([3, 3], 6), e: [0, 1] }, { l: "Larger array", r: (f) => f([1, 5, 3, 7, 9, 2], 8), e: [1, 5] }],
        },
        {
            id: "1b", title: "Max Subarray", diff: "Easy", xp: 120,
            desc: "Given an integer array `nums`, find the contiguous subarray which has the **largest sum** and return its sum.\n\nThis is the classic Kadane's Algorithm problem.",
            examples: [{ i: "nums=[-2,1,-3,4,-1,2,1,-5,4]", o: "6", e: "[4,-1,2,1] has the largest sum=6" }, { i: "nums=[1]", o: "1" }, { i: "nums=[-2,-1]", o: "-1" }],
            hints: ["Track both current subarray sum and global maximum", "If current sum goes negative, reset it to 0 (or current element)", "Kadane's: maxSoFar = max(nums[i], maxSoFar + nums[i])"],
            start: "function solve(nums) {\n  // Return the maximum subarray sum\n  \n}",
            tests: [{ l: "Mixed array", r: (f) => f([-2, 1, -3, 4, -1, 2, 1, -5, 4]), e: 6 }, { l: "Single element", r: (f) => f([1]), e: 1 }, { l: "All negative", r: (f) => f([-2, -1]), e: -1 }, { l: "All positive", r: (f) => f([1, 2, 3, 4, 5]), e: 15 }],
        },
        {
            id: "1c", title: "Best Time to Buy & Sell", diff: "Medium", xp: 150,
            desc: "Given an array `prices` where `prices[i]` is the price on day `i`, return the **maximum profit** you can achieve by buying on one day and selling on a later day.\n\nReturn 0 if no profit is possible.",
            examples: [{ i: "prices=[7,1,5,3,6,4]", o: "5", e: "Buy on day 2 (price=1), sell on day 5 (price=6), profit=5" }, { i: "prices=[7,6,4,3,1]", o: "0" }],
            hints: ["Track the minimum price seen so far", "For each price, calculate profit if you sold today", "Update max profit and min price as you iterate"],
            start: "function solve(prices) {\n  // Return maximum profit\n  \n}",
            tests: [{ l: "Classic case", r: (f) => f([7, 1, 5, 3, 6, 4]), e: 5 }, { l: "No profit", r: (f) => f([7, 6, 4, 3, 1]), e: 0 }, { l: "Single buy/sell", r: (f) => f([1, 2]), e: 1 }, { l: "Large gain", r: (f) => f([2, 4, 1, 7]), e: 6 }],
        },
    ],
    2: [
        {
            id: "2a", title: "Valid Palindrome", diff: "Easy", xp: 100,
            desc: "A phrase is a **palindrome** if, after converting all uppercase letters to lowercase and removing all non-alphanumeric characters, it reads the same forward and backward.\n\nGiven a string `s`, return `true` if it is a palindrome.",
            examples: [{ i: 's="A man, a plan, a canal: Panama"', o: "true" }, { i: 's="race a car"', o: "false" }],
            hints: ["Filter out non-alphanumeric chars and lowercase the string", "Use two pointers from both ends", "Or simply compare the cleaned string with its reverse"],
            start: "function solve(s) {\n  // Return true if palindrome\n  \n}",
            tests: [{ l: "Classic palindrome", r: (f) => f("A man, a plan, a canal: Panama"), e: true }, { l: "Not palindrome", r: (f) => f("race a car"), e: false }, { l: "Empty string", r: (f) => f(" "), e: true }, { l: "Single char", r: (f) => f("a"), e: true }],
        },
        {
            id: "2b", title: "Longest Substring Without Repeating", diff: "Medium", xp: 160,
            desc: "Given a string `s`, find the length of the **longest substring** without repeating characters.",
            examples: [{ i: 's="abcabcbb"', o: "3", e: '"abc" has length 3' }, { i: 's="bbbbb"', o: "1" }, { i: 's="pwwkew"', o: "3" }],
            hints: ["Use a sliding window approach", "Keep a Set of characters in the current window", "When duplicate found, shrink window from left"],
            start: "function solve(s) {\n  // Return length of longest substring\n  \n}",
            tests: [{ l: "Repeating chars", r: (f) => f("abcabcbb"), e: 3 }, { l: "All same", r: (f) => f("bbbbb"), e: 1 }, { l: "Mixed", r: (f) => f("pwwkew"), e: 3 }, { l: "Empty", r: (f) => f(""), e: 0 }],
        },
        {
            id: "2c", title: "Anagram Check", diff: "Easy", xp: 110,
            desc: "Given two strings `s` and `t`, return `true` if `t` is an **anagram** of `s`, and `false` otherwise.\n\nAn anagram uses the same letters in the same frequency, just rearranged.",
            examples: [{ i: 's="anagram", t="nagaram"', o: "true" }, { i: 's="rat", t="car"', o: "false" }],
            hints: ["Sort both strings and compare", "Or count character frequencies using an object", "Check length first as an early exit"],
            start: "function solve(s, t) {\n  // Return true if t is anagram of s\n  \n}",
            tests: [{ l: "Valid anagram", r: (f) => f("anagram", "nagaram"), e: true }, { l: "Not anagram", r: (f) => f("rat", "car"), e: false }, { l: "Different lengths", r: (f) => f("ab", "a"), e: false }, { l: "Same string", r: (f) => f("abc", "abc"), e: true }],
        },
    ],
    3: [
        {
            id: "3a", title: "Fibonacci Number", diff: "Easy", xp: 100,
            desc: "Given `n`, return the `n`th **Fibonacci number**.\n\nFibonacci: F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).\n\nSolve it **recursively**.",
            examples: [{ i: "n=2", o: "1", e: "F(2)=F(1)+F(0)=1" }, { i: "n=3", o: "2" }, { i: "n=10", o: "55" }],
            hints: ["Base cases: n===0 return 0, n===1 return 1", "Recursive case: return solve(n-1) + solve(n-2)", "Don't forget both base cases!"],
            start: "function solve(n) {\n  // Return nth Fibonacci number (recursively)\n  \n}",
            tests: [{ l: "F(2)", r: (f) => f(2), e: 1 }, { l: "F(5)", r: (f) => f(5), e: 5 }, { l: "F(10)", r: (f) => f(10), e: 55 }, { l: "F(0)", r: (f) => f(0), e: 0 }],
        },
        {
            id: "3b", title: "Power Function", diff: "Medium", xp: 140,
            desc: "Implement `pow(x, n)` which calculates `x` raised to the power `n` (i.e., x^n).\n\nSolve it **recursively** using fast exponentiation (divide-and-conquer).",
            examples: [{ i: "x=2, n=10", o: "1024" }, { i: "x=2, n=-2", o: "0.25" }, { i: "x=2, n=0", o: "1" }],
            hints: ["Base case: n===0 returns 1", "For even n: solve(x*x, n/2)", "For odd n: x * solve(x, n-1)", "Handle negative n: return 1/solve(x,-n)"],
            start: "function solve(x, n) {\n  // Return x^n recursively\n  \n}",
            tests: [{ l: "Positive power", r: (f) => f(2, 10), e: 1024 }, { l: "Negative power", r: (f) => f(2, -2), e: 0.25 }, { l: "Zero power", r: (f) => f(2, 0), e: 1 }, { l: "Power of 1", r: (f) => f(5, 1), e: 5 }],
        },
        {
            id: "3c", title: "Count Ways to Climb", diff: "Medium", xp: 150,
            desc: "You are climbing a staircase with `n` steps. Each time you can either climb **1** or **2** steps.\n\nReturn the number of distinct ways to reach the top. Solve **recursively** with memoization.",
            examples: [{ i: "n=2", o: "2", e: "(1+1) or (2)" }, { i: "n=3", o: "3", e: "(1+1+1),(1+2),(2+1)" }, { i: "n=5", o: "8" }],
            hints: ["This is essentially Fibonacci!", "ways(n) = ways(n-1) + ways(n-2)", "Use a memo object to cache results: memo[n] = result"],
            start: "function solve(n, memo={}) {\n  // Return number of distinct ways\n  \n}",
            tests: [{ l: "2 steps", r: (f) => f(2), e: 2 }, { l: "3 steps", r: (f) => f(3), e: 3 }, { l: "5 steps", r: (f) => f(5), e: 8 }, { l: "10 steps", r: (f) => f(10), e: 89 }],
        },
    ],
    4: [
        {
            id: "4a", title: "First Non-Repeating Char", diff: "Easy", xp: 110,
            desc: "Given a string `s`, find the **first non-repeating character** and return its index. If there is none, return `-1`.",
            examples: [{ i: 's="leetcode"', o: "0" }, { i: 's="loveleetcode"', o: "2" }, { i: 's="aabb"', o: "-1" }],
            hints: ["Count frequency of each character using an object", "Then iterate to find first char with frequency 1", "Two-pass solution: count first, then scan"],
            start: "function solve(s) {\n  // Return index of first unique character\n  \n}",
            tests: [{ l: "First char", r: (f) => f("leetcode"), e: 0 }, { l: "Middle char", r: (f) => f("loveleetcode"), e: 2 }, { l: "No unique", r: (f) => f("aabb"), e: -1 }, { l: "Single char", r: (f) => f("z"), e: 0 }],
        },
        {
            id: "4b", title: "Intersection of Two Arrays", diff: "Easy", xp: 120,
            desc: "Given two integer arrays `nums1` and `nums2`, return an array of their **intersection**.\n\nEach element in the result must appear as many times as it shows in both arrays.",
            examples: [{ i: "nums1=[1,2,2,1], nums2=[2,2]", o: "[2,2]" }, { i: "nums1=[4,9,5], nums2=[9,4,9,8,4]", o: "[4,9] or [9,4]" }],
            hints: ["Use a frequency map for nums1", "Iterate nums2, if element in map, add to result and decrement count", "Sort the result for consistency"],
            start: "function solve(nums1, nums2) {\n  // Return intersection array\n  \n}",
            tests: [
                { l: "Standard case", r: (f) => JSON.stringify(f([1, 2, 2, 1], [2, 2]).sort()), e: JSON.stringify([2, 2].sort()) },
                { l: "No intersection", r: (f) => JSON.stringify(f([1, 2], [3, 4]).sort()), e: JSON.stringify([]) },
                { l: "Full intersection", r: (f) => JSON.stringify(f([1, 2], [1, 2]).sort()), e: JSON.stringify([1, 2].sort()) },
                { l: "Duplicates", r: (f) => JSON.stringify(f([2, 2], [2, 2, 2]).sort()), e: JSON.stringify([2, 2].sort()) },
            ],
        },
        {
            id: "4c", title: "Subarray Sum Equals K", diff: "Medium", xp: 180,
            desc: "Given an array of integers `nums` and integer `k`, return the **total number of subarrays** whose sum equals `k`.",
            examples: [{ i: "nums=[1,1,1], k=2", o: "2" }, { i: "nums=[1,2,3], k=3", o: "2" }],
            hints: ["Use prefix sum + hash map technique", "Store {prefixSum: count} in a map", "For each element: if (prefixSum - k) exists in map, add its count"],
            start: "function solve(nums, k) {\n  // Return count of subarrays with sum k\n  \n}",
            tests: [{ l: "Basic case", r: (f) => f([1, 1, 1], 2), e: 2 }, { l: "Multiple subarrays", r: (f) => f([1, 2, 3], 3), e: 2 }, { l: "Negative nums", r: (f) => f([1, -1, 1], 1), e: 3 }, { l: "Single match", r: (f) => f([3, 4, 7], 7), e: 2 }],
        },
    ],
    5: [
        {
            id: "5a", title: "Valid Parentheses", diff: "Easy", xp: 110,
            desc: "Given a string `s` containing just `(`, `)`, `{`, `}`, `[`, `]`, determine if the input string is **valid**.\n\nAn input string is valid if open brackets are closed in the correct order.",
            examples: [{ i: 's="()"', o: "true" }, { i: 's="()[]{}"', o: "true" }, { i: 's="(]"', o: "false" }],
            hints: ["Use a stack (array)", "Push opening brackets onto stack", "For closing bracket, check if top of stack matches"],
            start: "function solve(s) {\n  // Return true if parentheses are valid\n  \n}",
            tests: [{ l: "Simple valid", r: (f) => f("()"), e: true }, { l: "Multi valid", r: (f) => f("()[]{}"), e: true }, { l: "Invalid mismatch", r: (f) => f("(]"), e: false }, { l: "Nested valid", r: (f) => f("{[()]}"), e: true }],
        },
        {
            id: "5b", title: "Reverse String with Stack", diff: "Easy", xp: 100,
            desc: "Using a **stack** data structure (implement as an array with push/pop), reverse a string `s`.\n\nDo not use built-in reverse methods.",
            examples: [{ i: 's="hello"', o: '"olleh"' }, { i: 's="Cyberpunk"', o: '"knuprepyC"' }],
            hints: ["Push all characters onto a stack", "Pop them one by one to build the result", "Stack is LIFO — last in, first out"],
            start: "function solve(s) {\n  // Return reversed string using a stack\n  \n}",
            tests: [{ l: "Hello", r: (f) => f("hello"), e: "olleh" }, { l: "Word", r: (f) => f("Cyberpunk"), e: "knuprepyC" }, { l: "Single char", r: (f) => f("a"), e: "a" }, { l: "Palindrome", r: (f) => f("racecar"), e: "racecar" }],
        },
        {
            id: "5c", title: "Daily Temperatures", diff: "Medium", xp: 170,
            desc: "Given an array of integers `temps` representing daily temperatures, return an array `answer` such that `answer[i]` is the number of days until a warmer temperature.\n\nIf no future warmer day exists, answer[i] = 0.",
            examples: [{ i: "temps=[73,74,75,71,69,72,76,73]", o: "[1,1,4,2,1,1,0,0]" }, { i: "temps=[30,40,50,60]", o: "[1,1,1,0]" }],
            hints: ["Use a monotonic stack storing indices", "While current temp > stack top temp, pop and compute distance", "Push current index onto stack"],
            start: "function solve(temps) {\n  // Return array of wait days\n  \n}",
            tests: [
                { l: "Classic case", r: (f) => JSON.stringify(f([73, 74, 75, 71, 69, 72, 76, 73])), e: JSON.stringify([1, 1, 4, 2, 1, 1, 0, 0]) },
                { l: "Ascending", r: (f) => JSON.stringify(f([30, 40, 50, 60])), e: JSON.stringify([1, 1, 1, 0]) },
                { l: "Descending", r: (f) => JSON.stringify(f([60, 50, 40, 30])), e: JSON.stringify([0, 0, 0, 0]) },
                { l: "Single", r: (f) => JSON.stringify(f([75])), e: JSON.stringify([0]) },
            ],
        },
    ],
    6: [
        {
            id: "6a", title: "Number of Recent Calls", diff: "Easy", xp: 120,
            desc: "You have a `RecentCounter` class. Implement `ping(t)` which adds a new request at time `t` and returns the number of requests in the range `[t-3000, t]`.\n\nFor this problem: solve(requests) should return array of counts after each ping.",
            examples: [{ i: "requests=[1,100,3001,3002]", o: "[1,2,3,3]" }],
            hints: ["Use a queue (array)", "For each ping, add t to queue", "Remove all entries less than (t-3000) from front"],
            start: "function solve(requests) {\n  const queue = [];\n  return requests.map(t => {\n    // Process each request\n    \n  });\n}",
            tests: [
                { l: "Classic case", r: (f) => JSON.stringify(f([1, 100, 3001, 3002])), e: JSON.stringify([1, 2, 3, 3]) },
                { l: "All in window", r: (f) => JSON.stringify(f([1, 2, 3, 4])), e: JSON.stringify([1, 2, 3, 4]) },
                { l: "Window slide", r: (f) => JSON.stringify(f([100, 3200, 3201])), e: JSON.stringify([1, 1, 2]) },
            ],
        },
        {
            id: "6b", title: "Moving Average", diff: "Easy", xp: 130,
            desc: "Given a stream of integers and a window size `k`, compute the **moving average** of all integers in the sliding window.\n\n`solve(nums, k)` returns array of moving averages (round to 2 decimal places).",
            examples: [{ i: "nums=[1,10,3,5], k=3", o: "[1.0, 5.5, 4.67, 6.0]" }],
            hints: ["Use a queue of size k", "When queue exceeds k, remove oldest element", "Maintain a running sum for efficiency"],
            start: "function solve(nums, k) {\n  // Return array of moving averages\n  \n}",
            tests: [
                { l: "Standard", r: (f) => JSON.stringify(f([1, 10, 3, 5], 3).map(x => Math.round(x * 100) / 100)), e: JSON.stringify([1, 5.5, 4.67, 6]) },
                { l: "Window=1", r: (f) => JSON.stringify(f([1, 2, 3], 1)), e: JSON.stringify([1, 2, 3]) },
                { l: "Window=all", r: (f) => JSON.stringify(f([1, 2, 3], 3).map(x => Math.round(x * 100) / 100)), e: JSON.stringify([1, 1.5, 2]) },
            ],
        },
        {
            id: "6c", title: "Task Scheduler", diff: "Hard", xp: 250,
            desc: 'Given a char array `tasks` and cooldown `n`, return the **minimum intervals** to finish all tasks.',
            examples: [{ i: 'tasks=["A","A","A","B","B","B"], n=2', o: "8" }, { i: 'tasks=["A","A","A","B","B","B"], n=0', o: "6" }],
            hints: ["Count frequency of each task", "Most frequent task determines minimum time", "Formula: max(tasks.length, (maxCount-1)*(n+1) + countOfMaxFreqTasks)"],
            start: "function solve(tasks, n) {\n  // Return minimum intervals needed\n  \n}",
            tests: [
                { l: "With cooldown", r: (f) => f(["A", "A", "A", "B", "B", "B"], 2), e: 8 },
                { l: "No cooldown", r: (f) => f(["A", "A", "A", "B", "B", "B"], 0), e: 6 },
                { l: "Single task", r: (f) => f(["A", "A", "A"], 2), e: 7 },
                { l: "Multiple max", r: (f) => f(["A", "A", "B", "B"], 2), e: 5 },
            ],
        },
    ],
    7: [
        {
            id: "7a", title: "Reverse Linked List", diff: "Easy", xp: 120,
            desc: "Given the head of a singly linked list (represented as an array), return it reversed.",
            examples: [{ i: "head=[1,2,3,4,5]", o: "[5,4,3,2,1]" }, { i: "head=[1,2]", o: "[2,1]" }],
            hints: ["Use prev, curr, next pointers", "Or simply reverse the array", "Iterative approach works well"],
            start: "function solve(head) {\n  // Return reversed linked list as array\n  \n}",
            tests: [
                { l: "5 nodes", r: (f) => JSON.stringify(f([1, 2, 3, 4, 5])), e: JSON.stringify([5, 4, 3, 2, 1]) },
                { l: "2 nodes", r: (f) => JSON.stringify(f([1, 2])), e: JSON.stringify([2, 1]) },
                { l: "Single", r: (f) => JSON.stringify(f([1])), e: JSON.stringify([1]) },
                { l: "Empty", r: (f) => JSON.stringify(f([])), e: JSON.stringify([]) },
            ],
        },
        {
            id: "7b", title: "Middle of Linked List", diff: "Easy", xp: 110,
            desc: "Given the head of a singly linked list (as array), return the **middle node's value**.\n\nIf two middle nodes exist, return the second middle.",
            examples: [{ i: "head=[1,2,3,4,5]", o: "3" }, { i: "head=[1,2,3,4,5,6]", o: "4" }],
            hints: ["Two-pointer technique: slow and fast", "Slow moves 1 step, fast moves 2 steps", "When fast reaches end, slow is at middle"],
            start: "function solve(head) {\n  // Return middle element value\n  \n}",
            tests: [{ l: "Odd length", r: (f) => f([1, 2, 3, 4, 5]), e: 3 }, { l: "Even length", r: (f) => f([1, 2, 3, 4, 5, 6]), e: 4 }, { l: "Single", r: (f) => f([1]), e: 1 }, { l: "Two nodes", r: (f) => f([1, 2]), e: 2 }],
        },
        {
            id: "7c", title: "Merge Two Sorted Lists", diff: "Medium", xp: 160,
            desc: "Merge two sorted linked lists (as arrays) into one **sorted list** and return it as an array.",
            examples: [{ i: "l1=[1,2,4], l2=[1,3,4]", o: "[1,1,2,3,4,4]" }, { i: "l1=[], l2=[0]", o: "[0]" }],
            hints: ["Use two pointers, one for each list", "Compare heads, take smaller, advance that pointer", "Don't forget to append remaining elements"],
            start: "function solve(l1, l2) {\n  // Return merged sorted array\n  \n}",
            tests: [
                { l: "Standard merge", r: (f) => JSON.stringify(f([1, 2, 4], [1, 3, 4])), e: JSON.stringify([1, 1, 2, 3, 4, 4]) },
                { l: "One empty", r: (f) => JSON.stringify(f([], [0])), e: JSON.stringify([0]) },
                { l: "Both empty", r: (f) => JSON.stringify(f([], [])), e: JSON.stringify([]) },
                { l: "No overlap", r: (f) => JSON.stringify(f([1, 2], [3, 4])), e: JSON.stringify([1, 2, 3, 4]) },
            ],
        },
    ],
    8: [
        {
            id: "8a", title: "Bubble Sort", diff: "Easy", xp: 110,
            desc: "Implement **Bubble Sort** on array `nums`. Return the sorted array.",
            examples: [{ i: "nums=[64,34,25,12,22,11,90]", o: "[11,12,22,25,34,64,90]" }],
            hints: ["Outer loop: n passes", "Inner loop: compare adjacent pairs", "If arr[j] > arr[j+1], swap them"],
            start: "function solve(nums) {\n  const arr = [...nums];\n  // Implement bubble sort\n  return arr;\n}",
            tests: [
                { l: "Classic case", r: (f) => JSON.stringify(f([64, 34, 25, 12, 22, 11, 90])), e: JSON.stringify([11, 12, 22, 25, 34, 64, 90]) },
                { l: "Already sorted", r: (f) => JSON.stringify(f([1, 2, 3, 4, 5])), e: JSON.stringify([1, 2, 3, 4, 5]) },
                { l: "Reverse sorted", r: (f) => JSON.stringify(f([5, 4, 3, 2, 1])), e: JSON.stringify([1, 2, 3, 4, 5]) },
                { l: "Single", r: (f) => JSON.stringify(f([1])), e: JSON.stringify([1]) },
            ],
        },
        {
            id: "8b", title: "Merge Sort", diff: "Medium", xp: 170,
            desc: "Implement **Merge Sort** — a divide-and-conquer sorting algorithm. Return the sorted array.",
            examples: [{ i: "nums=[38,27,43,3,9,82,10]", o: "[3,9,10,27,38,43,82]" }],
            hints: ["Base case: array of length 0 or 1 is already sorted", "Split array at midpoint: left and right halves", "Merge: compare front elements of both halves, take smaller"],
            start: "function solve(nums) {\n  // Implement merge sort recursively\n  \n}",
            tests: [
                { l: "Classic case", r: (f) => JSON.stringify(f([38, 27, 43, 3, 9, 82, 10])), e: JSON.stringify([3, 9, 10, 27, 38, 43, 82]) },
                { l: "Already sorted", r: (f) => JSON.stringify(f([1, 2, 3])), e: JSON.stringify([1, 2, 3]) },
                { l: "Reverse", r: (f) => JSON.stringify(f([5, 4, 3, 2, 1])), e: JSON.stringify([1, 2, 3, 4, 5]) },
                { l: "Duplicates", r: (f) => JSON.stringify(f([3, 1, 3, 2])), e: JSON.stringify([1, 2, 3, 3]) },
            ],
        },
        {
            id: "8c", title: "Sort Colors", diff: "Medium", xp: 180,
            desc: "Given an array `nums` with values 0, 1, or 2, sort them **in-place** in order 0, 1, 2. Dutch National Flag algorithm.",
            examples: [{ i: "nums=[2,0,2,1,1,0]", o: "[0,0,1,1,2,2]" }, { i: "nums=[2,0,1]", o: "[0,1,2]" }],
            hints: ["Three pointers: low, mid, high", "nums[mid]===0: swap with low, advance both", "nums[mid]===2: swap with high, decrement high", "nums[mid]===1: advance mid"],
            start: "function solve(nums) {\n  const arr = [...nums];\n  // Sort in-place using Dutch National Flag\n  return arr;\n}",
            tests: [
                { l: "Classic case", r: (f) => JSON.stringify(f([2, 0, 2, 1, 1, 0])), e: JSON.stringify([0, 0, 1, 1, 2, 2]) },
                { l: "Short array", r: (f) => JSON.stringify(f([2, 0, 1])), e: JSON.stringify([0, 1, 2]) },
                { l: "All same", r: (f) => JSON.stringify(f([1, 1, 1])), e: JSON.stringify([1, 1, 1]) },
                { l: "Two twos first", r: (f) => JSON.stringify(f([2, 2, 0, 0])), e: JSON.stringify([0, 0, 2, 2]) },
            ],
        },
    ],
    9: [
        {
            id: "9a", title: "Binary Search", diff: "Easy", xp: 100,
            desc: "Given a **sorted** array of integers `nums` and a `target`, return the index if found. If not, return `-1`. Must be O(log n).",
            examples: [{ i: "nums=[-1,0,3,5,9,12], target=9", o: "4" }, { i: "nums=[-1,0,3,5,9,12], target=2", o: "-1" }],
            hints: ["Set left=0 and right=nums.length-1", "mid = Math.floor((left+right)/2)", "If nums[mid]===target, return mid; if less, left=mid+1; if greater, right=mid-1"],
            start: "function solve(nums, target) {\n  // Implement binary search\n  \n}",
            tests: [{ l: "Found in middle", r: (f) => f([-1, 0, 3, 5, 9, 12], 9), e: 4 }, { l: "Not found", r: (f) => f([-1, 0, 3, 5, 9, 12], 2), e: -1 }, { l: "First element", r: (f) => f([1, 2, 3, 4, 5], 1), e: 0 }, { l: "Last element", r: (f) => f([1, 2, 3, 4, 5], 5), e: 4 }],
        },
        {
            id: "9b", title: "Search Insert Position", diff: "Easy", xp: 110,
            desc: "Given a sorted array `nums` and a `target`, return the index if found. If not, return the index where it **would be inserted** to maintain order.",
            examples: [{ i: "nums=[1,3,5,6], target=5", o: "2" }, { i: "nums=[1,3,5,6], target=2", o: "1" }, { i: "nums=[1,3,5,6], target=7", o: "4" }],
            hints: ["Use binary search", "When loop ends, left pointer is the insert position", "Edge cases: target smaller than all, or larger than all"],
            start: "function solve(nums, target) {\n  // Return index or insert position\n  \n}",
            tests: [{ l: "Found", r: (f) => f([1, 3, 5, 6], 5), e: 2 }, { l: "Insert middle", r: (f) => f([1, 3, 5, 6], 2), e: 1 }, { l: "Insert end", r: (f) => f([1, 3, 5, 6], 7), e: 4 }, { l: "Insert start", r: (f) => f([1, 3, 5, 6], 0), e: 0 }],
        },
        {
            id: "9c", title: "Peak Element", diff: "Medium", xp: 160,
            desc: "A **peak element** is one that is strictly greater than its neighbors. Return the index of any peak element. Solve in O(log n) time.",
            examples: [{ i: "nums=[1,2,3,1]", o: "2" }, { i: "nums=[1,2,1,3,5,6,4]", o: "1 or 5" }],
            hints: ["Use binary search on the array", "If nums[mid] < nums[mid+1], peak is to the right", "Otherwise, peak is to the left (or at mid)"],
            start: "function solve(nums) {\n  // Return index of any peak element\n  \n}",
            tests: [
                { l: "Simple peak", r: (f) => { const i = f([1, 2, 3, 1]); return i > 0 && i < 3 && [1, 2, 3, 1][i] > [1, 2, 3, 1][i - 1] && [1, 2, 3, 1][i] > [1, 2, 3, 1][i + 1]; }, e: true },
                { l: "Multiple peaks", r: (f) => { const a = [1, 2, 1, 3, 5, 6, 4]; const i = f(a); return a[i] > (a[i - 1] ?? -Infinity) && a[i] > (a[i + 1] ?? -Infinity); }, e: true },
                { l: "Single elem", r: (f) => f([1]), e: 0 },
                { l: "Two elems", r: (f) => { const i = f([2, 1]); return i === 0; }, e: true },
            ],
        },
    ],
    10: [
        {
            id: "10a", title: "Max Depth of Binary Tree", diff: "Easy", xp: 120,
            desc: "Given a binary tree represented as an array in level-order (null for missing nodes), return its **maximum depth**.",
            examples: [{ i: "tree=[3,9,20,null,null,15,7]", o: "3" }, { i: "tree=[1,null,2]", o: "2" }],
            hints: ["For array representation, use DFS with left=2*i+1, right=2*i+2", "Recursive: 1 + max(depth(left), depth(right))"],
            start: "function solve(tree) {\n  function dfs(i) {\n    if (i >= tree.length || tree[i] === null) return 0;\n    return 1 + Math.max(dfs(2*i+1), dfs(2*i+2));\n  }\n  return dfs(0);\n}",
            tests: [{ l: "3 levels", r: (f) => f([3, 9, 20, null, null, 15, 7]), e: 3 }, { l: "2 levels", r: (f) => f([1, null, 2]), e: 2 }, { l: "Single", r: (f) => f([1]), e: 1 }, { l: "4 levels", r: (f) => f([1, 2, 3, 4, 5, 6, 7]), e: 3 }],
        },
        {
            id: "10b", title: "Same Tree", diff: "Easy", xp: 120,
            desc: "Given two binary trees (as level-order arrays), check whether they are the **same**.",
            examples: [{ i: "p=[1,2,3], q=[1,2,3]", o: "true" }, { i: "p=[1,2], q=[1,null,2]", o: "false" }],
            hints: ["Use DFS with index arithmetic", "Compare values at each node", "Both null = equal; one null = not equal"],
            start: "function solve(p, q) {\n  function same(i) {\n    const pv = i < p.length ? p[i] : null;\n    const qv = i < q.length ? q[i] : null;\n    if (pv === null && qv === null) return true;\n    if (pv !== qv) return false;\n    return same(2*i+1) && same(2*i+2);\n  }\n  return same(0);\n}",
            tests: [{ l: "Same trees", r: (f) => f([1, 2, 3], [1, 2, 3]), e: true }, { l: "Different structure", r: (f) => f([1, 2], [1, null, 2]), e: false }, { l: "Different values", r: (f) => f([1, 2, 1], [1, 1, 2]), e: false }, { l: "Both empty", r: (f) => f([], []), e: true }],
        },
        {
            id: "10c", title: "Level Order Traversal", diff: "Medium", xp: 170,
            desc: "Given a binary tree (level-order array), return its **level order traversal** as an array of arrays.",
            examples: [{ i: "tree=[3,9,20,null,null,15,7]", o: "[[3],[9,20],[15,7]]" }, { i: "tree=[1]", o: "[[1]]" }],
            hints: ["Use BFS with a queue", "Track level boundaries", "For each level, collect all non-null children"],
            start: "function solve(tree) {\n  if (!tree.length || tree[0] === null) return [];\n  const result = [];\n  const queue = [0];\n  while (queue.length) {\n    const level = [];\n    const size = queue.length;\n    for (let k = 0; k < size; k++) {\n      const i = queue.shift();\n      if (i < tree.length && tree[i] !== null) {\n        level.push(tree[i]);\n        if (2*i+1 < tree.length && tree[2*i+1] !== null) queue.push(2*i+1);\n        if (2*i+2 < tree.length && tree[2*i+2] !== null) queue.push(2*i+2);\n      }\n    }\n    if (level.length) result.push(level);\n  }\n  return result;\n}",
            tests: [
                { l: "3 levels", r: (f) => JSON.stringify(f([3, 9, 20, null, null, 15, 7])), e: JSON.stringify([[3], [9, 20], [15, 7]]) },
                { l: "Single", r: (f) => JSON.stringify(f([1])), e: JSON.stringify([[1]]) },
                { l: "Full tree", r: (f) => JSON.stringify(f([1, 2, 3, 4, 5, 6, 7])), e: JSON.stringify([[1], [2, 3], [4, 5, 6, 7]]) },
            ],
        },
    ],
    11: [
        {
            id: "11a", title: "Number of Islands", diff: "Medium", xp: 200,
            desc: "Given a 2D grid of '1's (land) and '0's (water), count the **number of islands**.",
            examples: [{ i: 'grid=[["1","1","0"],["1","1","0"],["0","0","1"]]', o: "2" }, { i: 'grid=[["1","1","1","1","0"]]', o: "1" }],
            hints: ["Use DFS or BFS from each unvisited '1'", "Mark visited cells to avoid counting twice"],
            start: "function solve(grid) {\n  let count = 0;\n  function dfs(r, c) {\n    if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length || grid[r][c] !== '1') return;\n    grid[r][c] = '0';\n    dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1);\n  }\n  for (let r = 0; r < grid.length; r++)\n    for (let c = 0; c < grid[0].length; c++)\n      if (grid[r][c] === '1') { count++; dfs(r, c); }\n  return count;\n}",
            tests: [{ l: "2 islands", r: (f) => f([["1", "1", "0"], ["1", "1", "0"], ["0", "0", "1"]]), e: 2 }, { l: "1 island", r: (f) => f([["1", "1", "1", "1", "0"]]), e: 1 }, { l: "No land", r: (f) => f([["0", "0", "0"]]), e: 0 }, { l: "All land", r: (f) => f([["1", "1"], ["1", "1"]]), e: 1 }],
        },
        {
            id: "11b", title: "BFS Shortest Path", diff: "Medium", xp: 220,
            desc: "Given a 2D binary `grid` (0=free, 1=wall), find the **shortest path** from top-left to bottom-right. Return path length or -1.",
            examples: [{ i: "grid=[[0,0,0],[1,1,0],[1,1,0]]", o: "5" }, { i: "grid=[[0,1],[1,0]]", o: "-1" }],
            hints: ["Use BFS — it guarantees shortest path", "Queue starts with [[0,0,1]]", "Mark visited cells to avoid revisiting"],
            start: "function solve(grid) {\n  const R = grid.length, C = grid[0].length;\n  if (grid[0][0] === 1 || grid[R-1][C-1] === 1) return -1;\n  const visited = Array.from({length:R}, ()=>new Array(C).fill(false));\n  const queue = [[0,0,1]];\n  visited[0][0] = true;\n  while (queue.length) {\n    const [r, c, d] = queue.shift();\n    if (r === R-1 && c === C-1) return d;\n    for (const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]) {\n      const nr=r+dr, nc=c+dc;\n      if (nr>=0&&nc>=0&&nr<R&&nc<C&&!visited[nr][nc]&&grid[nr][nc]===0) {\n        visited[nr][nc]=true; queue.push([nr,nc,d+1]);\n      }\n    }\n  }\n  return -1;\n}",
            tests: [{ l: "Path exists", r: (f) => f([[0, 0, 0], [1, 1, 0], [1, 1, 0]]), e: 5 }, { l: "Blocked", r: (f) => f([[0, 1], [1, 0]]), e: -1 }, { l: "1x1 grid", r: (f) => f([[0]]), e: 1 }, { l: "Straight path", r: (f) => f([[0, 0, 0], [0, 0, 0], [0, 0, 0]]), e: 5 }],
        },
        {
            id: "11c", title: "Clone Graph", diff: "Hard", xp: 280,
            desc: "Given an adjacency list `graph`, perform a **deep clone**. Return the cloned adjacency list.",
            examples: [{ i: "graph=[[1,2],[0,3],[0,3],[1,2]]", o: "[[1,2],[0,3],[0,3],[1,2]]" }, { i: "graph=[[]]", o: "[[]]" }],
            hints: ["Use BFS or DFS with a visited map", "Map original node → cloned node"],
            start: "function solve(graph) {\n  if (!graph.length) return [];\n  // Deep clone the adjacency list\n  return graph.map(neighbors => [...neighbors]);\n}",
            tests: [
                { l: "4-node graph", r: (f) => JSON.stringify(f([[1, 2], [0, 3], [0, 3], [1, 2]])), e: JSON.stringify([[1, 2], [0, 3], [0, 3], [1, 2]]) },
                { l: "Empty node", r: (f) => JSON.stringify(f([[]])), e: JSON.stringify([[]]) },
                { l: "Linear chain", r: (f) => JSON.stringify(f([[1], [0, 2], [1]])), e: JSON.stringify([[1], [0, 2], [1]]) },
            ],
        },
    ],
};
